module.exports=[
    {
        "_id":1001,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.4 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','S','L','XL'],
        "price":2999,
        "color":["Blue","Green"],
        "image":["/images/men/m1.png","/images/men/m2.png","/images/men/m3.png"],
        "discount":22,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1002,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.5 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m2.png","/images/men/m1.png","/images/men/m3.png"],
        "discount":12,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1003,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":3.7 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','S','M','L'],
        "price":2499,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m3.png","/images/men/m2.png","/images/men/m1.png"],
        "discount":18,
        "quantity":55,
        "shippingCharges":49
    },
   
    {
        "_id":1004,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.1 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['S','M','L','XL'],
        "price":3999,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m4.png","/images/men/m2.png","/images/men/m3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1005,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":3.9 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','M','L','XL'],
        "price":3499,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m5.png","/images/men/m1.png","/images/men/m3.png"],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1006,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":5.0 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','S','XL'],
        "price":4999,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m6.png","/images/men/m2.png","/images/men/m1.png"],
        "discount":25,
        "quantity":55,
        "shippingCharges":49
    },
   
    {
        "_id":1007,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.2 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['M','L','XL'],
        "price":2299,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m7.png","/images/men/m2.png","/images/men/m3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1008,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.5 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['XS','S','L'],
        "price":3999,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m8.png","/images/men/m1.png","/images/men/m3.png"],
        "discount":10,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1009,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.7 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['XS','M','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m9.png","/images/men/m2.png","/images/men/m1.png"],
        "discount":12,
        "quantity":55,
        "shippingCharges":49
    },
   
    {
        "_id":1010,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":3.2 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['S','M','L'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m10.png","/images/men/m2.png","/images/men/m3.png"],
        "discount":30,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1011,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.1 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['XS','M','L','XL'],
        "price":2599,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m11.png","/images/men/m1.png","/images/men/m3.png"],
        "discount":18,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1012,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.7 ,
        "idealFor":"men",
        "category":"Formal",
        "size":['XS','S','M','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m12.png","/images/men/m2.png","/images/men/m1.png"],
        "discount":24,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1013,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.0 ,
        "idealFor":"men",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":3299,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m13.png","/images/men/m2.png","/images/men/m3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1014,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.5 ,
        "idealFor":"men",
        "category":"Formal",
        "size":['XS','S','M','L'],
        "price":3499,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m14.png","/images/men/m1.png","/images/men/m3.png"],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1015,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.3 ,
        "idealFor":"men",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/men/m15.png","/images/men/m2.png","/images/men/m1.png"],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1016,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.4 ,
        "idealFor":"women",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w1.png","/images/women/w2.png","/images/women/w3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1017,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.5 ,
        "idealFor":"women",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":2999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w2.png","/images/women/w1.png","/images/women/w3.png"],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1018,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.7 ,
        "idealFor":"women",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w3.png","/images/women/w2.png","/images/women/w1.png"],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1019,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.4 ,
        "idealFor":"women",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w4.png","/images/women/w2.png","/images/women/w3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1020,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.5 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":2999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w5.png","/images/women/w1.png","/images/women/w3.png"],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1021,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.7 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w6.png","/images/women/w2.png","/images/women/w1.png"],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1022,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.4 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w7.png","/images/women/w2.png","/images/women/w3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1023,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.5 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":2999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w8.png","/images/women/w1.png","/images/women/w3.png"],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1024,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.7 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/women/w9.png","/images/women/w2.png","/images/women/w1.png"],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1025,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.4 ,
        "idealFor":"kids",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/kids/k1.png","/images/kids/k2.png","/images/kids/k3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1026,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.5 ,
        "idealFor":"kids",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":2999,
        "color":["Red","Blue","Green"],
        "image":["/images/kids/k2.png","/images/kids/k1.png","/images/kids/k3.png"],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1027,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.7 ,
        "idealFor":"kids",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/kids/k3.png","/images/kids/k2.png","/images/kids/k1.png"],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1028,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.4 ,
        "idealFor":"kids",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/kids/k4.png","/images/kids/k2.png","/images/kids/k3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1029,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.5 ,
        "idealFor":"kids",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":2999,
        "color":["Red","Blue","Green"],
        "image":["/images/kids/k5.png","/images/kids/k1.png","/images/kids/k3.png"],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1030,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.7 ,
        "idealFor":"kids",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/kids/k6.png","/images/kids/k2.png","/images/kids/k1.png"],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1031,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.4 ,
        "idealFor":"kids",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["/images/kids/k7.png","/images/kids/k2.png","/images/kids/k3.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
]
